/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 02:06:20 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "=|KV3a:7M^:", "=|KV3a:7M^:");
      String string0 = appt0.toString();
      assertEquals("\t11/11/11 at 11:11am ,=|KV3a:7M^:, =|KV3a:7M^:\n", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(1271, 1271, 0, 0, 1, "--", "--");
      boolean boolean0 = appt0.getValid();
      assertEquals("--", appt0.getDescription());
      assertEquals(0, appt0.getStartDay());
      assertFalse(boolean0);
      assertEquals(1271, appt0.getStartHour());
      assertEquals("--", appt0.getTitle());
      assertEquals(1271, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(1, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(77, (-469), 77, 77, (-469), (String) null, (String) null);
      int int0 = appt0.getStartYear();
      assertFalse(appt0.getValid());
      assertEquals(-469, appt0.getStartMinute());
      assertEquals(77, appt0.getStartHour());
      assertEquals((-469), int0);
      assertEquals(77, appt0.getStartMonth());
      assertEquals(77, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt((-1053), (-1053), (-1053), 0, (-3715), "", "O\u0001");
      int int0 = appt0.getStartMonth();
      assertEquals(-3715, appt0.getStartYear());
      assertEquals(0, int0);
      assertEquals(-1053, appt0.getStartDay());
      assertEquals("", appt0.getTitle());
      assertEquals("O\u0001", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(-1053, appt0.getStartHour());
      assertEquals(-1053, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(12, 0, 12, 12, 12, "", "");
      int int0 = appt0.getStartMonth();
      assertEquals(12, int0);
      assertEquals(12, appt0.getStartHour());
      assertEquals(12, appt0.getStartYear());
      assertEquals(12, appt0.getStartDay());
      assertEquals(0, appt0.getStartMinute());
      assertTrue(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "%h:%m:%s%z", "$]aF");
      int int0 = appt0.getStartMinute();
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartYear());
      assertEquals("$]aF", appt0.getDescription());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartDay());
      assertEquals("%h:%m:%s%z", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt(60000, 60000, 60000, 60000, 0, "1^", "1^");
      int int0 = appt0.getStartMinute();
      assertEquals(60000, appt0.getStartDay());
      assertEquals(0, appt0.getStartYear());
      assertEquals(60000, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals(60000, appt0.getStartHour());
      assertEquals(60000, int0);
      assertEquals("1^", appt0.getDescription());
      assertEquals("1^", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, (-566), "", "PLQm>L$d:&1Cy,v3>[");
      int int0 = appt0.getStartHour();
      assertEquals(-566, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
      assertEquals("PLQm>L$d:&1Cy,v3>[", appt0.getDescription());
      assertEquals(0, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, int0);
      assertEquals("", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(16, 0, (-3474), 0, 60000, (String) null, (String) null);
      int int0 = appt0.getStartHour();
      assertEquals(16, int0);
      assertEquals(60000, appt0.getStartYear());
      assertEquals(-3474, appt0.getStartDay());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "_", "_");
      int int0 = appt0.getStartDay();
      assertEquals("_", appt0.getTitle());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals("_", appt0.getDescription());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(1970, 1970, 6562, 1970, 1970, "t_CdUt>:RAcwUci4g", "t_CdUt>:RAcwUci4g");
      int int0 = appt0.getStartDay();
      assertEquals(6562, int0);
      assertEquals(1970, appt0.getStartMonth());
      assertEquals(1970, appt0.getStartMinute());
      assertEquals(1970, appt0.getStartYear());
      assertEquals("t_CdUt>:RAcwUci4g", appt0.getDescription());
      assertEquals(1970, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals("t_CdUt>:RAcwUci4g", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "_", "_");
      appt0.setDescription("_");
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartDay());
      assertEquals("_", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartMinute());
      assertEquals("_", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt(2092, 2092, 2092, 2092, 2092, "D7=", "D7=");
      assertEquals("D7=", appt0.getDescription());
      
      appt0.setDescription((String) null);
      assertEquals(2092, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt((-40), (-40), (-306), 1465, 1465, "Z7xX{*3: ;1z", "'sN~ m7n-9968:");
      appt0.setTitle("Z7xX{*3: ;1z");
      assertEquals(-40, appt0.getStartMinute());
      assertEquals(1465, appt0.getStartYear());
      assertEquals(1465, appt0.getStartMonth());
      assertEquals(-306, appt0.getStartDay());
      assertEquals("Z7xX{*3: ;1z", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals("'sN~ m7n-9968:", appt0.getDescription());
      assertEquals(-40, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 11, 11, 2745, "|KV3a:7M^:", "|KV3a:7M^:");
      assertEquals("|KV3a:7M^:", appt0.getTitle());
      
      appt0.setTitle((String) null);
      appt0.getTitle();
      assertTrue(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 11, 11, 2745, "|KV3a:7M^:", "|KV3a:7M^:");
      String string0 = appt0.getTitle();
      assertEquals(2745, appt0.getStartYear());
      assertEquals("|KV3a:7M^:", string0);
      assertEquals(11, appt0.getStartDay());
      assertTrue(appt0.getValid());
      assertEquals(0, appt0.getStartHour());
      assertEquals(11, appt0.getStartMonth());
      assertEquals(0, appt0.getStartMinute());
      assertEquals("|KV3a:7M^:", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt((-427), (-606), (-427), (-427), 12, "c", "c");
      int int0 = appt0.getStartDay();
      assertEquals("c", appt0.getTitle());
      assertEquals(-427, appt0.getStartHour());
      assertEquals((-427), int0);
      assertEquals(-606, appt0.getStartMinute());
      assertEquals("c", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(-427, appt0.getStartMonth());
      assertEquals(12, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt(12, 0, 12, 12, 12, "", "");
      boolean boolean0 = appt0.getValid();
      assertEquals(0, appt0.getStartMinute());
      assertEquals(12, appt0.getStartDay());
      assertEquals(12, appt0.getStartYear());
      assertEquals(12, appt0.getStartHour());
      assertTrue(boolean0);
      assertEquals(12, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt((-40), (-40), (-306), 1465, 1465, "Z7xX{*3: ;1z", "'sN~ m7n-9968:");
      int int0 = appt0.getStartHour();
      assertEquals(-306, appt0.getStartDay());
      assertEquals("Z7xX{*3: ;1z", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals("'sN~ m7n-9968:", appt0.getDescription());
      assertEquals(1465, appt0.getStartYear());
      assertEquals(-40, appt0.getStartMinute());
      assertEquals(1465, appt0.getStartMonth());
      assertEquals((-40), int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "'NsE", "'NsE");
      int int0 = appt0.getStartYear();
      assertEquals("'NsE", appt0.getDescription());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals("'NsE", appt0.getTitle());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, (String) null, (String) null);
      String string0 = appt0.getDescription();
      assertEquals(1, appt0.getStartMinute());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1, appt0.getStartDay());
      assertEquals(1, appt0.getStartYear());
      assertEquals(1, appt0.getStartHour());
      assertTrue(appt0.getValid());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt((-1), (-1), (-1), (-1), (-1), "", "");
      int int0 = appt0.getStartMonth();
      assertEquals((-1), int0);
      assertFalse(appt0.getValid());
      assertEquals(-1, appt0.getStartYear());
      assertEquals(-1, appt0.getStartHour());
      assertEquals(-1, appt0.getStartDay());
      assertEquals(-1, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, "", "");
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t1/1/1 at 1:1am ,, \n", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "yuhK!3082q .KU|q0", "yuhK!3082q .KU|q0");
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t12/12/12 at 12:12pm ,yuhK!3082q .KU|q0, yuhK!3082q .KU|q0\n", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 11, 11, 2745, "|KV3a:7M^:", "|KV3a:7M^:");
      appt0.setStartHour((-2208));
      appt0.toString();
      assertEquals(-2208, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 23, 23, "%Y-%M-%DT%h:%m:%s%z", "%Y-%M-%DT%h:%m:%s%z");
      String string0 = appt0.getDescription();
      assertEquals(23, appt0.getStartYear());
      assertEquals("%Y-%M-%DT%h:%m:%s%z", string0);
      assertEquals(23, appt0.getStartMinute());
      assertEquals(23, appt0.getStartMonth());
      assertEquals(23, appt0.getStartHour());
      assertEquals(23, appt0.getStartDay());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt(0, 59, 59, 59, 59, (String) null, "pm");
      int int0 = appt0.getStartYear();
      assertEquals(59, appt0.getStartMinute());
      assertEquals(59, appt0.getStartMonth());
      assertEquals("pm", appt0.getDescription());
      assertEquals(0, appt0.getStartHour());
      assertEquals(59, int0);
      assertEquals("", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(59, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(10, (-2928), (-2928), (-2928), 10, "08}\"pF|v", "08}\"pF|v");
      assertEquals("08}\"pF|v", appt0.getDescription());
      assertEquals(10, appt0.getStartHour());
      assertEquals(-2928, appt0.getStartMinute());
      assertEquals(-2928, appt0.getStartDay());
      assertEquals(10, appt0.getStartYear());
      assertEquals("08}\"pF|v", appt0.getTitle());
      assertEquals(-2928, appt0.getStartMonth());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "_", "_");
      appt0.setStartMinute(0);
      assertEquals("_", appt0.getDescription());
      assertEquals(0, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals("_", appt0.getTitle());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 31, 0, 31, (String) null, (String) null);
      appt0.setStartYear((-62));
      assertEquals(-62, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(77, (-469), 77, 77, (-469), (String) null, (String) null);
      assertEquals(77, appt0.getStartDay());
      
      appt0.setStartDay((-469));
      assertEquals(-469, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(2092, 2092, 2092, 2092, 2092, "D7=", "D7=");
      appt0.setStartHour(0);
      assertEquals(0, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Appt appt0 = new Appt(77, (-469), 77, 77, (-469), (String) null, (String) null);
      assertEquals(77, appt0.getStartMonth());
      
      appt0.setStartMonth((-469));
      assertEquals(-469, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Appt appt0 = new Appt((-3274), (-3274), 0, (-3274), 0, "i9.}5[!izF6G^.#", "i9.}5[!izF6G^.#");
      int int0 = appt0.getStartMinute();
      assertEquals(-3274, appt0.getStartHour());
      assertEquals(0, appt0.getStartDay());
      assertEquals("i9.}5[!izF6G^.#", appt0.getTitle());
      assertEquals("i9.}5[!izF6G^.#", appt0.getDescription());
      assertEquals((-3274), int0);
      assertEquals(-3274, appt0.getStartMonth());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }
}
